"""Ingest: pull upstream data into the raw cache and clean it into canonical tables."""

from epl.ingest.fixtures import (
    FIXTURE_COLUMNS,
    FIXTURES_URL,
    fetch_fixtures,
    latest_fixtures_path,
    parse_fixtures,
)
from epl.ingest.football_data import (
    DIVISIONS,
    FIRST_SEASON,
    LAST_SEASON,
    MATCH_COLUMNS,
    SOURCE,
    IngestError,
    club_names_in_raw_cache,
    fetch_all,
    fetch_season,
    load_matches,
    parse_season_csv,
    raw_season_path,
    read_raw_csv,
    season_code,
    season_csv_url,
    season_label,
)

__all__ = [
    "DIVISIONS",
    "FIRST_SEASON",
    "FIXTURES_URL",
    "FIXTURE_COLUMNS",
    "LAST_SEASON",
    "MATCH_COLUMNS",
    "SOURCE",
    "IngestError",
    "club_names_in_raw_cache",
    "fetch_all",
    "fetch_fixtures",
    "fetch_season",
    "latest_fixtures_path",
    "load_matches",
    "parse_fixtures",
    "parse_season_csv",
    "raw_season_path",
    "read_raw_csv",
    "season_code",
    "season_csv_url",
    "season_label",
]
