"""Ingest: pull upstream data into the raw cache and clean it into canonical tables."""

from epl.ingest.fetcher import (
    Fetcher,
    default_fetcher,
    directory_fetcher,
    http_fetcher,
    mapping_fetcher,
)
from epl.ingest.fixtures import (
    FIXTURE_COLUMNS,
    FIXTURES_URL,
    fetch_fixtures,
    latest_fixtures_path,
    parse_fixtures,
)
from epl.ingest.football_data import (
    DIVISIONS,
    MATCH_COLUMNS,
    ODDS_AVAILABILITY_COLUMNS,
    SOURCE,
    IngestError,
    club_names_in_raw_cache,
    fetch_all,
    fetch_season,
    load_matches,
    odds_availability,
    odds_availability_for,
    parse_season_csv,
    raw_season_path,
    read_raw_csv,
    season_code,
    season_csv_url,
    superseded_dir,
)
from epl.windows import FIRST_SEASON, LAST_SEASON, season_label

__all__ = [
    "DIVISIONS",
    "FIRST_SEASON",
    "FIXTURES_URL",
    "FIXTURE_COLUMNS",
    "LAST_SEASON",
    "MATCH_COLUMNS",
    "ODDS_AVAILABILITY_COLUMNS",
    "SOURCE",
    "Fetcher",
    "IngestError",
    "club_names_in_raw_cache",
    "default_fetcher",
    "directory_fetcher",
    "fetch_all",
    "fetch_fixtures",
    "fetch_season",
    "http_fetcher",
    "latest_fixtures_path",
    "load_matches",
    "mapping_fetcher",
    "odds_availability",
    "odds_availability_for",
    "parse_fixtures",
    "parse_season_csv",
    "raw_season_path",
    "read_raw_csv",
    "season_code",
    "season_csv_url",
    "season_label",
    "superseded_dir",
]
