"""A machine that has sealed a round, as the bot finds one.

The bot answers from this project's own stores, so what it needs on disk is what the Pi has: a
sealed round under `outputs/live/`, and the match table `python -m epl.live score` rebuilds. What
the Pi does *not* have is `outputs/backtest/` — it is gitignored, it is regenerated by a command
nothing schedules, and `tests/bot/test_answers.py` has a test about exactly that absence.

The round modelled here is `outputs/live/2026-08-28.csv`, cut down: two Fixtures rather than ten,
and the same four Predictors that spoke on the real one. Five were silent, which is the permanent
answer for anything unplayed (stage 12), and the message has to say so.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

from epl.ledger import schema
from epl.paths import live_dir, processed_dir

#: The Predictors that spoke on the first real Sealed Prediction Round, in the order the file
#: holds them. The other five say nothing about an unplayed Fixture and say so themselves
#: (`epl.live.seal`).
SPOKE: tuple[str, ...] = ("dixon_coles", "elo", "market_line", "naive_baseline")

#: The round, its As-Of Instant and its two Fixtures — the real round's first two.
ROUND = "2026-08-28"
AS_OF = "2026-08-28T00:00:00"
FIXTURES: tuple[tuple[str, str, str], ...] = (
    ("2026-08-28T20:00:00", "crystal_palace", "man_city"),
    ("2026-08-29T12:30:00", "liverpool", "nottm_forest"),
)

#: One quote per Predictor, distinct enough that a message quoting the wrong one is visible.
QUOTES: dict[str, tuple[float, float, float]] = {
    "dixon_coles": (0.18, 0.23, 0.59),
    "elo": (0.21, 0.25, 0.54),
    "market_line": (0.19, 0.24, 0.57),
    "naive_baseline": (0.46, 0.26, 0.28),
}


def sealed_rows(prediction_round: str = ROUND, as_of: str = AS_OF) -> pd.DataFrame:
    """One round's Sealed Predictions, in `epl.ledger.schema`'s shape."""
    rows = [
        {
            "predictor": predictor,
            "prediction_round": prediction_round,
            "as_of_instant": as_of,
            "season": 2026,
            "division": "E0",
            "kickoff": kickoff,
            "home_club": home,
            "away_club": away,
            "prob_home": home_probability,
            "prob_draw": draw,
            "prob_away": away_probability,
            # A Market Line reads its odds off the Fixture and consumes no history, so it records
            # nothing seen — which is correct and is on the real file too (CLAUDE.md).
            "inputs_seen": 0 if predictor == "market_line" else 52754,
            "latest_input": pd.NaT if predictor == "market_line" else "2026-08-24T20:00:00",
        }
        for kickoff, home, away in FIXTURES
        for predictor in SPOKE
        for home_probability, draw, away_probability in [QUOTES[predictor]]
    ]
    return schema.conform(pd.DataFrame(rows))


@pytest.fixture
def sealed_store(project_root: Path) -> pd.DataFrame:
    """A store holding one sealed round, written the way the loop writes one."""
    live_dir().mkdir(parents=True)
    rows = sealed_rows()
    rows.to_csv(live_dir() / f"{ROUND}.csv", index=False, date_format=schema.DATE_FORMAT)
    return rows


@pytest.fixture
def corpus(project_root: Path, make_matches) -> Path:  # type: ignore[no-untyped-def]
    """A match table in which the round's first Fixture has been played and the second has not.

    Which is the ordinary state of a Sunday: the bot has to score what it can and say nothing about
    what it cannot, rather than treat an unplayed Fixture as a missing result.
    """
    matches = make_matches(
        {
            "season": 2026,
            "date": "2026-08-28",
            "home_club": "crystal_palace",
            "away_club": "man_city",
            "home_goals": 0,
            "away_goals": 2,
            "outcome": "A",
        },
        {
            "season": 2026,
            "date": "2026-08-22",
            "home_club": "arsenal",
            "away_club": "everton",
            "home_goals": 3,
            "away_goals": 0,
            "outcome": "H",
        },
    )
    processed_dir().mkdir(parents=True, exist_ok=True)
    destination = processed_dir() / "matches.csv"
    matches.to_csv(destination, index=False)
    return destination


@pytest.fixture
def registered_predictors() -> None:
    """Every Predictor on the registry, which is what a running bot has.

    The bot answers from the registry rather than from a list of its own — that is what makes a
    `note` travel with its Predictor and a silent Predictor be named — so a test of any message is
    a test against whatever is registered, and registering nothing would pass by vacuum.
    """
    import epl.ledger as ledger

    ledger.register_all()
